#!/usr/bin/env node

'use strict';

let path = require('path')
let fs = require('fs')
let util = require('util')

let lunr = require('lunr')

let alltags = require('../../src/tags')

let parse_tags = function(line) {
    return line.split(',').map(function(val) { return val.trim() })
}

let tags_union = function(a, b) {
    return a.concat(b.filter(function (item) {
	return a.indexOf(item) < 0
    }))
}

let data_index_of = function(data, id) {
    for (let idx in data) {
	if (data[idx].id === id) return idx
    }
    return -1
}

let tags_stem = function(pair) {
    if (pair[0] && pair[1]) {
	let p1 = lunr.stemmer(pair[0])
	let p2 = lunr.stemmer(pair[1])
	if (p1 === p2) {
	    // return the shortest word
	    return [pair[0].length < pair[1].length ? pair[0] : pair[1]]
	}
    }
    return pair
}

let conf = {
    index: 0
}

let parse = function(file) {
    let data = []
    let text = fs.readFileSync(file).toString().split("\n")

    let tags = []
    let cache = {}
    for (let line of text) {
	if (line.match(/^(\s*$|#.*)$/)) continue // comments & empty lines

	if (!line.match(/[.?!]/)) {
	    tags = tags_stem(parse_tags(line))
	    continue
	}

	// 'line' contains a proverb
	let parts = line.trim().match(/^(.+)\s+\((.+?)\)$/)
	let proverb = parts[1]
	let ctags = tags_union(tags, parse_tags(parts[2]))
	if (proverb in cache) {
	    // append new tags to an existing entry
	    let idx = data_index_of(data, cache[proverb])
	    data[idx].t = tags_union(data[idx].t, ctags)
	} else {
	    data.push({
		id: conf.index,
		p: proverb,
		t: ctags,
		bo: alltags.bo_get(ctags)
	    })

	    cache[proverb] = conf.index++
	}
    }

    return data
}


/*
  CLI
*/

let usage = function() {
    console.error(`Usage: ${path.basename(process.argv[1])} file1.txt [file2.txt ...]`)
    process.exit(1)
}

if (process.argv.length < 3) usage()

let arr = process.argv.slice(2).map(parse)
//console.log(util.inspect(arr[0], { depth: null }))
//console.log(alltags.misc(arr[0]))
let arrflat = arr.reduce(function(a, b) { return a.concat(b) })
process.stdout.write(JSON.stringify(arrflat))
